# Цвета
COLOR_BG = "#050505"
COLOR_INACTIVE = "#2a2a2a"
COLOR_ACTIVE = "#40E0D0"       # бирюзовый/голубой
COLOR_FRAME = "#D4AF37"        # золотой
COLOR_BUTTON_ACTIVE = "#40E0D0"
COLOR_BUTTON_INACTIVE = "#333333"
COLOR_BUTTON_DISABLED = "#1a1a1a"

# Шрифт
FONT_FAMILY = "Consolas, 'Courier New', monospace"
FONT_SIZE = 20

# Размеры сетки
CELL_SIZE = 26
GRID_COLS = 11
GRID_ROWS = 10
GRID_WIDTH = GRID_COLS * CELL_SIZE
GRID_HEIGHT = GRID_ROWS * CELL_SIZE

# Окно
WINDOW_PADDING = 16
BUTTON_SIZE = 10
BUTTON_MARGIN = 6
